include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - 'lib/stateHolders/matrixSelectionHolder.dart'
    - 'lib/token/tokenmodel.dart'
    - 'lib/components/widgets/list_view_new.dart'
    - 'lib/components/Input/*'
    - 'lib/ui/test/*'
    - 'lib/provider/auth/word_generator.dart'
  errors:
    invalid_assignment: error
linter:
  rules:
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - avoid_shadowing_type_parameters
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - empty_constructor_bodies
    - library_names
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_checks
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_string_buffers
