name: Flutter CI

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different
  pull_request:
    branches:
      - main  # Replace 'main' with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
          flutter-version: '3.7.5'
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          .pub-cache
          .dart_tool
          **/android/.gradle
          **/ios/Pods
          **/build
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test

    - name: Analyze code
      run: flutter analyze

    - name: Build app
      run: flutter build apk
